### ISSUE TITLE
concourse: build and use custom docker images

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1863]
Currently, every task in the master and PR pipelines need to `bundle install` which is pretty wasteful. Additionally, the rubinius and valgrind builds run `apt update` and apt-install packages.

Instead, let's generate a docker image for each version of ruby with the gems and apt packages pre-installed.

For extra credit, maybe this is done in a new pipeline that triggers when either:
* a new upstream ruby or jruby docker image is created,
* or when the gemspec changes. (See https://github.com/flavorjones/hoe-gemspec/issues/1 for how that might be done.)

I think this will not only decrease our load on third-party servers, but also dramatically speed up our builds.

### Tasks

- [x] docker build system for MRI
  - [x] apt update
  - [x] libxml
  - [x] valgrind
  - [x] bundle install
- [x] docker build system for JRuby
  - [x] java opts
  - [x] bundle install
- [x] docker build system for vanilla ubuntu/xenial
  - [x] ruby-dev and bundler
- [x] remove rubinius for now (it's been segfaulting for nearly a year)
  - make this one commit so we can bring it back later
- [x] remove unnecessary installation stuff from `rake-test/run.sh`

**Comment by flavorjones** [comment]
See proof-of-concept at https://github.com/flavorjones/calendar-assistant/commit/4e01a0f09ad1051fbdd641e4edd3d9c49e929dd8

**Comment by flavorjones** [comment]
:shipit:
