### ISSUE TITLE
Epic: merge Nokogumbo into Nokogiri

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#2204]
The maintainers of Nokogiri and Nokogumbo are planning to merge the two gems together so that Nokogiri assimilates Nokogumbo's HTML5 parsing functionality.

This issue is intended to be a "parent" issue which can be followed to understand the plan and how it's progressing, as the work will likely take O(weeks) and will be on a feature branch driven by multiple PRs.

This description will be edited as we go to reflect current state and progress.

## Background

This work has previously been discussed:

* #2064
* https://github.com/rubys/nokogumbo/issues/170

## Goals

Here's what success looks like:

* Nokogiri v1.12 supports HTML5 parsing using Nokogumbo's API, code, and fork of Gumbo.
* The Nokogumbo maintainers feel welcomed into the Nokogiri maintainer team.
* Upgrade paths for users are easy to navigate, and users don't get "stuck" on old versions.
* The Gumbo parser ships as a precompiled library in all the native platform gems supported by Nokogiri v1.11.
* The end-state of Nokogumbo is a (mostly) empty gem that prompts users to replace their dependency on Nokogumbo with Nokogiri.

For more specific objectives, see the "Punchlist" section below.

## Note: No JRuby support at this time

> :warning: **JRuby support is *not* going to be addressed as part of this work.** However, we feel it is important to think about and we hope to work on this in the future. If you're interested in helping with HTML5 support on JRuby, please comment on this issue or ping the maintainers on [the mailing list or the Discord channel](https://nokogiri.org/tutorials/getting_help.html#ask-for-help).

The Nokogumbo code relies on a parser implemented in C, and a C extension that is tightly coupled to libxml2. As a result, the `Nokogiri::HTML5` module will not be immediately available on JRuby, which uses Xerces in place of libxml2.

We ask that all downstream libraries be aware of this platform limitation as they consider using `HTML5` parsing methods post-merger.

## Risks

This work doesn't feel very risky, but if I had to name the riskiest bits:

* Precompiling Gumbo for all our platforms might be challenging.
* Gumbo is no longer supported upstream by Google, so we are assuming responsibility for keeping it secure, performant, and up-to-date with the HTML5 spec.
* There's no way to prevent using a new Nokogiri with an old Nokogumbo and seeing lots of annoying "constant redefined" warning messages.

Some things that could have been risky but aren't:

* License compatibility.
  * The Nokogumbo license is APL2.0. APL2.0 is compatible with MIT, and so we will maintain that license for specific files, preserving the notices required by APL2.0. We are already doing this with several files in the JRuby Java implementation.

## Frequently Asked Questions

_Why is this going into v1.12 and not v2.0?_

This is not a breaking change. We want everyone on v1.11 to upgrade, and will be making efforts to make that upgrade painless.

_Will Nokogiri's current HTML API or parsing behavior change?_

No. Nokogiri's existing HTML parsing functionality, available under the `Nokogiri::HTML` module/namespace, will not change in this release. The Nokogumbo additions to Nokogiri are all contained under the `Nokogiri::HTML5` module/namespace, and do not conflict with existing Nokogiri functionality.

In the future, we may explore how Nokogiri might be smarter about HTML4 versus HTML5 parsing, but those changes will be introduced carefully. See some more thoughts on this topic at https://github.com/sparklemotion/nokogiri/issues/2064#issuecomment-686627509

_Will JRuby support HTML5?_

Not initially, though we hope to work on this for a future release. See the section above for more information.

## Punchlist

Some finer-grained objectives (which will be modified over time as we discover new work to be done):

### Pre-merger

* [x] Release Nokogumbo version which no-ops if Nokogiri is providing HTML5 functionality

### Team Merger

* [x] Nokogumbo contributors are added to the Nokogiri gemspec, README, and copyright declarations.
* [x] Nokogumbo contributors are added to @sparklemotion/nokogiri-core 
* [x] Send some welcome gifts to the Nokogumbo maintainers.

### Legal/License Merger

* [x] All nokogumbo files should mention they are originally licensed under Apache 2.0 (an interpretation of APL2.0 clause 4.c) and mention that they have been changed (clause 4.b)
* [x] Changed gumbo-parser files should "carry prominent notices stating that You changed the files" (APL2.0 clause 4.b)
  * I believe this intention is covered by `gumbo-parser/src/README.md`
* [x] Update `LICENSE-DEPENDENCIES.md` to include gumbo and nokogumbo under Apache License 2.0 (APL2.0 clause 4.a)

### Functional Merger

* [x] Commit history for Nokogumbo is preserved in the Nokogiri repository.
* [x] Unit tests include an integration contract for https://github.com/rubys/nokogumbo/pull/171
* [x] Nokogumbo unit tests integrated into `rake test`
* [x] Nokogumbo's HTML5 files moved into `lib/nokogiri` and C file moved into `ext/nokogiri`
* [x] extconf.rb builds Nokogumbo and Gumbo into `nokogiri.so`
* [x] Nokogumbo unit tests are green on a dev system
* [x] Valgrind memory testing is green on HTML5 functionality
* [x] Gumbo can be precompiled for linux 64-bit and 32-bit.
* [x] Gumbo can be precompiled for windows 64-bit and 32-bit.
* [x] Gumbo can be precompiled for darwin x64-64 and arm64.
* [x] Gumbo can be compiled from the vanilla gem on platforms without a native gem.
* [x] Import the html5lib tests into the repository and the test suite, and get it green in CI
* [x] Run the gumbo parser tests on all platforms
* [x] Integrate test coverage platform breadth from Nokogumbo's CI

### Forward-looking Changes
- [x] deprecate `Nokogiri::HTML5.get`
- [x] introduce `Nokogiri::HTML4` as an alias for `Nokogiri::HTML` so that at some point we can deprecate and change the `HTML` functionality (#2278)

### Pre-release

* [x] HTML5 rdocs should note that the API is available only starting in v1.12, and only in CRuby (not JRuby).
* [x] `/nokogumbo-import` contents should either be deleted or moved somewhere else
* [x] examine the exported symbols, which include many `gumbo_` symbols. do these need to be exported?
* [x] Update #2205 for people coming from a Nokogumbo warning message
* [x] #2279
* [x] https://github.com/sparklemotion/nokogiri/pull/2281
* [x] Update README and Tutorials

### Release candidate

* [x] :shipit: - https://github.com/sparklemotion/nokogiri/releases/tag/v1.12.0.rc1
* [x] solicit feedback in a Discussion thread - https://github.com/sparklemotion/nokogiri/discussions/2289

### Final release

* [x] :shipit: 

---
/cc @rubys @stevecheckoway

**Comment by SamSaffron** [comment]
This is great news! Thank you!

**Comment by flavorjones** [comment]
Punch list updates:

- Release Nokogumbo version which no-ops if Nokogiri is providing HTML5 functionality: https://github.com/rubys/nokogumbo/releases/tag/v2.0.5
- Nokogumbo contributors are added to @sparklemotion/nokogiri-core

Also see https://github.com/sparklemotion/nokogiri/pull/2217 which merges the code and commit history (parked on a branch until I release v1.11.3).

**Comment by hino-ryu** [comment]
> The maintainers of Nokogiri and Nokogumbo are planning to merge the two gems together so that Nokogiri assimilates Nokogumbo's HTML5 parsing functionality.
> 
> This issue is intended to be a "parent" issue which can be followed to understand the plan and how it's progressing, as the work will likely take O(weeks) and will be on a feature branch driven by multiple PRs.
> 
> This description will be edited as we go to reflect current state and progress.
> 
> ## Background
> This work has previously been discussed:
> 
> * [RFC: Explore alternatives to libxml2 for HTML parsing · Issue #2064 · sparklemotion/nokogiri](https://github.com/sparklemotion/nokogiri/issues/2064)
> * [RFC: How to prepare for a future merge of nokogumbo into the nokogiri gem · Issue #170 · rubys/nokogumbo](https://github.com/rubys/nokogumbo/issues/170)
> 
> ## Goals
> Here's what success looks like:
> 
> * Nokogiri v1.12 supports HTML5 parsing using Nokogumbo's API, code, and fork of Gumbo.
> * The Nokogumbo maintainers feel welcomed into the Nokogiri maintainer team.
> * Upgrade paths for users are easy to navigate, and users don't get "stuck" on old versions.
> * The Gumbo parser ships as a precompiled library in all the native platform gems supported by Nokogiri v1.11.
> * The end-state of Nokogumbo is a (mostly) empty gem that prompts users to replace their dependency on Nokogumbo with Nokogiri.
> 
> For more specific objectives, see the "Punchlist" section below.
> 
> ## Note: No JRuby support at this time
> > ⚠️ **JRuby support is _not_ going to be addressed as part of this work.** However, we feel it is important to think about and we hope to work on this in the future. If you're interested in helping with HTML5 support on JRuby, please comment on this issue or ping the maintainers on [the mailing list or the Discord channel](https://nokogiri.org/tutorials/getting_help.html#ask-for-help).
> 
> The Nokogumbo code relies on a parser implemented in C, and a C extension that is tightly coupled to libxml2. As a result, the `Nokogiri::HTML5` module will not be immediately available on JRuby, which uses Xerces in place of libxml2.
> 
> We ask that all downstream libraries be aware of this platform limitation as they consider using `HTML5` parsing methods post-merger.
> 
> ## Risks
> This work doesn't feel very risky, but if I had to name the riskiest bits:
> 
> * Precompiling Gumbo for all our platforms might be challenging.
> * Gumbo is no longer supported upstream by Google, so we are assuming responsibility for keeping it secure, performant, and up-to-date with the HTML5 spec.
> * There's no way to prevent using a new Nokogiri with an old Nokogumbo and seeing lots of annoying "constant redefined" warning messages.
> 
> Some things that could have been risky but aren't:
> 
> * License compatibility.
>   
>   * The Nokogumbo license is APL2.0. APL2.0 is compatible with MIT, and so we will maintain that license for specific files, preserving the notices required by APL2.0. We are already doing this with several files in the JRuby Java implementation.
> 
> ## Frequently Asked Questions
> _Why is this going into v1.12 and not v2.0?_
> 
> This is not a breaking change. We want everyone on v1.11 to upgrade, and will be making efforts to make that upgrade painless.
> 
> _Will Nokogiri's current HTML API or parsing behavior change?_
> 
> No. Nokogiri's existing HTML parsing functionality, available under the `Nokogiri::HTML` module/namespace, will not change in this release. The Nokogumbo additions to Nokogiri are all contained under the `Nokogiri::HTML5` module/namespace, and do not conflict with existing Nokogiri functionality.
> 
> In the future, we may explore how Nokogiri might be smarter about HTML4 versus HTML5 parsing, but those changes will be introduced carefully. See some more thoughts on this topic at [#2064 (comment)](https://github.com/sparklemotion/nokogiri/issues/2064#issuecomment-686627509)
> 
> _Will JRuby support HTML5?_
> 
> Not initially, though we hope to work on this for a future release. See the section above for more information.
> 
> ## Punchlist
> Some finer-grained objectives (which will be modified over time as we discover new work to be done):
> 
> ### Pre-merger
> * [x]  Release Nokogumbo version which no-ops if Nokogiri is providing HTML5 functionality
> 
> ### Team Merger
> * [x]  Nokogumbo contributors are added to the Nokogiri gemspec, README, and copyright declarations.
> * [x]  Nokogumbo contributors are added to @sparklemotion/nokogiri-core
> * [x]  Send some welcome gifts to the Nokogumbo maintainers.
> 
> ### Legal/License Merger
> * [x]  All nokogumbo files should mention they are originally licensed under Apache 2.0 (an interpretation of APL2.0 clause 4.c) and mention that they have been changed (clause 4.b)
> * [ ]  Changed gumbo-parser files should "carry prominent notices stating that You changed the files" (APL2.0 clause 4.b)
> * [ ]  Update `LICENSE-DEPENDENCIES.md` to include gumbo and nokogumbo under Apache License 2.0 (APL2.0 clause 4.a)
> 
> ### Functional Merger
> * [x]  Commit history for Nokogumbo is preserved in the Nokogiri repository.
> * [x]  Unit tests include an integration contract for [rubys/nokogumbo#171](https://github.com/rubys/nokogumbo/pull/171)
> * [x]  Nokogumbo unit tests integrated into `rake test`
> * [x]  Nokogumbo's HTML5 files moved into `lib/nokogiri` and C file moved into `ext/nokogiri`
> * [x]  extconf.rb builds Nokogumbo and Gumbo into `nokogiri.so`
> * [x]  Nokogumbo unit tests are green on a dev system
> * [x]  Valgrind memory testing is green on HTML5 functionality
> * [x]  Gumbo can be precompiled for linux 64-bit and 32-bit.
> * [x]  Gumbo can be precompiled for windows 64-bit and 32-bit.
> * [x]  Gumbo can be precompiled for darwin x64-64 and arm64.
> * [x]  Gumbo can be compiled from the vanilla gem on platforms without a native gem.
> * [ ]  Integrate test coverage platform breadth from Nokogumbo's CI
> * [ ]  Import the html5lib tests into the repository and the test suite, and get it green in CI
> 
> ### Pre-release
> * [ ]  Alias `Nokogiri::HTML4` to `Nokogiri::HTML` to prepare for possibly changing default behavior in a future release.
> * [ ]  HTML5 rdocs should note that the API is available only starting in v1.12, and only in CRuby (not JRuby).
> * [ ]  Update README and Tutorials
> * [ ]  Update #2205 for people coming from a Nokogumbo warning message
> * [ ]  Integration test with Nokogumbo v2.0.4 (with warnings) and v2.0.5 (without warnings)
> 
> /cc @rubys @stevecheckoway

**Comment by flavorjones** [comment]
Just a quick update!

Work on completing this integration got held up because I spent some time moving Nokogiri's CI to Github Actions (#2207, #2244, #2247, #2226) and improving the test coverage around gem packaging and installation (#1718, #2151, #2152, #2153).

Now that that's done (see https://github.com/sparklemotion/nokogiri/actions), I'm in a good place to pick this back up and merge Nokogumbo's actions-based test suite. Hopefully this will go quickly, since the bulk of the work is done and I'd love to ship a release candidate and get some feedback.

**Comment by flavorjones** [comment]
@stevecheckoway You mentioned [in another thread](https://github.com/rubys/nokogumbo/issues/170#issuecomment-797616327) that you'd like the html5lib-tests to be imported from your fork+branch. Is that still what you'd prefer? An alternative (or intermediate step) might be to submodule it.

Another question: it looks like html5lib-tests is still active, meaning that it's drifted since your fork. Are you thinking about rebasing at all? What's your mental model for how those tests should be maintained going forward?

**Comment by stevecheckoway** [comment]
A submodule seems fine. It'd be great if they would respond to my pull requests either accept the changes or reject them. But based on my reading of the errors (a part of the spec that's in flux), the tests were wrong. I'll look at rebasing.

**Comment by flavorjones** [comment]
Submodule sounds good to me, too. See #2273.

**Comment by stevecheckoway** [comment]
I just rebased my `all-error-fixes` branch of html5lib-tests and discovered that a new test was added that changes the test format. Previously, comments always appeared on one line, now they can appear on multiple lines.

There are also some new tree-building tests that don't pass. I looked at one and I don't see how the test matches the spec (but does agree with the browser). I'll follow up on that and see if I can figure out what the issue is.

Here's an example of the new tests that are failing: `<math></p><foo>` This should produce the DOM:
```
<html>
  <body>
    <math>
    <p>
    <foo>
```
but my reading (and gumbo's code) produce
```
<html>
  <body>
    <math>
      <p>
      <foo>
```
That is, the `p` and `foo` elements should be children of `body` according to the test but are being parsed as children of `math`.

**Comment by stevecheckoway** [comment]
I asked about it on the pull request that introduced the tests. https://github.com/html5lib/html5lib-tests/pull/135

**Comment by flavorjones** [comment]
@stevecheckoway OK, thanks for looking into it. I have #2273 which I should finish today, and once that's done it'll be on `main` for you to do with as you please.

**Comment by flavorjones** [comment]
Everything from the "Functional Merger" section of this issue's description is done and on `main`.

**Comment by stevecheckoway** [comment]
I dug into it a little more. Safari, Firefox, and Chrome all agree with the test. `html5ever` agrees with Gumbo and my reading of the spec. More details [here](https://github.com/html5lib/html5lib-tests/pull/135#discussion_r654826232). This could be a spec bug, so I filed an [issue](https://github.com/whatwg/html/issues/6788). It's more likely I'm just missing something subtle.

**Comment by stevecheckoway** [comment]
It predates my involvement with the project. I don't use it myself.

**Comment by flavorjones** [comment]
OK, everything except updating the tutorials is done, which I think means we should ship a release candidate and ask people to give feedback (likely in a "Discussion" thread).

@sparklemotion/nokogiri-core Let me know if there's anything y'all think we need to do before cutting that release candidate, or if there's anything missing from the list in this issue. Otherwise, I'll cut a release in the next day or so.

**Comment by rubys** [comment]
> I'd like to "deprecate" the method Nokogiri::HTML5.get

Perhaps just delete it as it never shipped with Nokogiri?

As to mental model: I have a number of apps that parse HTML.  Guess where the largest source of HTML would be.  :-). You guessed it: the internet.  So this was a common enough use case to factor out of the application and into a gem.

If it doesn't belong in the nokogiri gem, a new gem could always be created to include this function.  This is a common pattern with Rails: things that were once core but no longer are considered core are moved out into gems.

P.S.  Sorry for the delay in responding.

**Comment by flavorjones** [comment]
> Perhaps just delete it as it never shipped with Nokogiri?

Yeah,I thought about it, but it's been in Nokogumbo since 2013, and the pledge we're making with this integration is that apps can drop the dependency on Nokogumbo and everything will Just Work™. I don't want to support the method, but I also don't want to introduce any unnecessary hurdles to upgrade/adoption.

In 4ac9350 I introduced a warning, and I think that's sufficient for now.

**Comment by flavorjones** [comment]
I've shipped a release candidate at [v1.12.0.rc1](https://github.com/sparklemotion/nokogiri/releases/tag/v1.12.0.rc1), and started a [discussion](https://github.com/sparklemotion/nokogiri/discussions/2289).

Please let us know any feedback either here or in that discussion thread!

**Comment by flavorjones** [comment]
Planning to ship v1.12 final this coming weekend, around July 31st.

**Comment by flavorjones** [comment]
Nokogiri v1.12.0 has shipped. Closing.

https://github.com/sparklemotion/nokogiri/releases/tag/v1.12.0
