### ISSUE TITLE
long tail of CI jobs

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#2247]
Split out from #2244, here's the long tail of lower-priority CI jobs and cI-related chores:

Build actions for:

- [x] nightly builds against libxml2 master - #2256 
- [x] get basic tests running: truffleruby - #2270
- [ ] ~move generation of docker images to GA and use the Github Registry~
- [ ] ~stop generating docker images for platforms no longer needed (like jruby)~

Final steps:

- [x] remove Concourse pipeline configs, rake config, and gem dependency - #2269
- [x] remove any webhooks configured to ping concourse (e.g., PR or push)
- [x] set required checks for merging PRs onto `main`
- [x] update `CONTRIBUTING.md` section on CI - 909954b
- [x] turn off code climate coverage, remove the badge from the readme - #2269 

Note gaps relative to previous coverage:

- Installing gems on alpine/musl and on 32-bit linux (because `actions/download-artifact` won't run there, see https://github.com/actions/checkout/issues/334)

**Comment by flavorjones** [comment]
Remaining work pushed to #2271
