### ISSUE TITLE
Epic: merge nokogiri-xmlsec into Nokogiri

### ISSUE THREAD

**Issue by maths22** [sparklemotion/nokogiri#2902]
The maintainers of Nokogiri and nokogiri-xmlsec-instructure are planning to merge the two gems together so that Nokogiri assimilates xmlsec's signing and encryption features.

This issue is intended to be a "parent" issue which can be followed to understand the plan and how it's progressing, as the work will likely take O(weeks) and will be on a feature branch driven by multiple PRs.

This description will be edited as we go to reflect current state and progress.

## Background

This work has previously been discussed:

* https://github.com/sparklemotion/nokogiri/discussions/2746#discussioncomment-5561385
* https://github.com/sparklemotion/nokogiri/discussions/2896

As indicated in the first discussion, the underlying motivation is to allow nokogiri to stop exporting the symbols of the underlying native libraries when compiled with libxml2, libxslt, and friends.  (Question: to facilitate potential future innovation, do we want to continue to export nokogiri's own symbols when compiled to use system libraries where the symbol export issues are irrelevant?)

## Goals

Here's what success looks like:

* Nokogiri v1.xy supports xmlsec encryption/decrption and signing/validation using the code from nokogiri-xmlsec-instructure.=
* Upgrade paths for users are easy to navigate, and users don't get "stuck" on old versions.
* Xmlsec and a crypto dependency (probably openssl) ships as a precompiled library in all the native platform gems supported by Nokogiri v1.xx.
* The end-state of nokogiri-xmlsec-instructure is a (mostly) empty gem that prompts users to replace their dependency on nokogiri-xmlsec-instructure.

For more specific objectives, see the "Punchlist" section below.

## Note: No JRuby support at this time

> :warning: **JRuby support is *not* going to be addressed as part of this work.** However, we hope to work on this in the future. 

The nokogiri-xmlsec code relies on an xmlsec implementation in C, and a C extension that is tightly coupled to libxml2. As a result, the `xmlsec` methods will not be immediately available on JRuby, which uses Xerces in place of libxml2.  We should be able to use https://santuario.apache.org/ in place of xmlsec1, but that exploration will be in a future release.

We ask that all downstream libraries be aware of this platform limitation as they consider using `HTML5` parsing methods post-merger.

## Risks

This work doesn't feel very risky, but if I had to name the riskiest bits:

* Precompiling xmlsec's crypto dependnecies for all our platforms might be challenging.

Some things that could have been risky but aren't:

* License compatibility.
  * The nokogiri-xmlsec-instructure license is MIT. Since nokogiri is also MIT, we don't need to worry about compatiblity, just including the necessary copyright notice (the upstream repo just says `Copyright (c) 2013 TODO: Write your name`, so maybe we don't need to carry *that* forward?).
  * The xmlsec license is MIT. Since nokogiri is also MIT, we don't need to worry about compatiblity, just including the necessary notice for binary distributions.
  * The openssl license is APL2.0. APL2.0 is compatible with MIT, so we just need to include the necessary notice for binary distributions.
  * (we could theoretically explore using a different crypto provider instead, but all seem worse license-wise)

## Punchlist

Some finer-grained objectives (which will be modified over time as we discover new work to be done):

### Pre-merger

* [ ] Release nokogiri-xmlsec-instructure version which no-ops if Nokogiri is providing xmlsec functionality (not sure if we need this for this initiative or not)

### Team Merger

@flavorjones (this section was copy-pasted from nokogumbo, and I don't know if it actually applies to this work; please edit appropriately)
* [ ] Nokogumbo contributors are added to the Nokogiri gemspec, README, and copyright declarations.
* [ ] Nokogumbo contributors are added to @sparklemotion/nokogiri-core 
* [ ] Send some welcome gifts to the Nokogumbo maintainers.

### Legal/License Merger

* [ ] All nokogiri-xmlsec files should possibly include a header with their original copyright (see note above re: current copyright)
* [ ] Update `LICENSE-DEPENDENCIES.md` to include xmlsec under MIT
* [ ] Update `LICENSE-DEPENDENCIES.md` to include openssl under Apache License 2.0 (APL2.0 clause 4.a)

### Functional Merger

* [ ] Commit history for nokogiri-xmlsec-instructure is preserved in the Nokogiri repository. (given scale I don't know if this is actually valuable?)
* [ ] Unit tests include an integration contract for nokogiri-xmlsec equivalent of https://github.com/rubys/nokogumbo/pull/171
* [ ] nokogiri-xmlsec-instructure unit tests integrated into `rake test`
* [ ] nokogiri-xmlsec-instructure rb files moved into `lib/nokogiri` and C file moved into `ext/nokogiri`
* [ ] extconf.rb builds xmlsec/openssl into `nokogiri.so`
* [ ] nokogiri-xmlsec-instructure unit tests are green on a dev system
* [ ] Valgrind memory testing is green on xmlsec functionality
* [ ] xmlsec/openssl can be precompiled for linux 64-bit and 32-bit.
* [ ] xmlsec/openssl can be precompiled for windows 64-bit and 32-bit.
* [ ] xmlsec/openssl can be precompiled for darwin x64-64 and arm64.
* [ ] xmlsec/openssl can be compiled from the vanilla gem on platforms without a native gem.

### Pre-release

* [ ] HTML5 rdocs should note that the API is available only starting in v1.xy, and only in CRuby (not JRuby).
* [ ] Update README and Tutorials

### Release candidate

* [ ] :shipit:
* [ ] solicit feedback in a Discussion thread

### Final release

* [ ] :shipit:

**Comment by johnnyshields** [comment]
RubySaml maintainer here. This would be wonderful to have!

**Comment by flavorjones** [comment]
@johnnyshields Can you say more about your use case, please? What prompted you to comment? Would you be willing to help out?

**Comment by johnnyshields** [comment]
SAML protocol is based on top of the XML encryption and signing which xml-sec handles. It would be great for RubySaml if those parts of the codebase could be delegated, and we wouldn't have to worry as much about potential vulnerabilities in our own signing functions

**Comment by flavorjones** [comment]
@johnnyshields I'm curious, would it be a problem for you if Nokogiri only support xml-sec in CRuby? I know you've been trying hard to maintain JRuby support, but because I'm not a JRuby user I personally have very little interest in adding new Java native code to the gem.

Though I would be happy to accept help and contributions from folks who do use JRuby!

**Comment by johnnyshields** [comment]
It would not be a problem, we have a pure Ruby implementation that we would keep for JRuby.

**Comment by ccutrer** [comment]
@flavorjones: I've started working on this, and have gotten past the critical point where the ci.yml workflow passes all the various platform builds with xmlsec with and without using system libraries. My question is... do you think I should add a `--without-xmlsec` option? I feel like some users could benefit from it, since both a) xmlsec has far less broad appeal than Nokogumbo, and b) the dependencies for xmlsec are larger than Gumbo - mainly because of OpenSSL. I'm _not_ currently packaging OpenSSL directly into the gem like libxml2 and libxslt, since it's almost always present with (C) Ruby, and I'm worried that doing so might cause weird conflicts with having two versions of it loaded into the same process.

**Comment by flavorjones** [comment]
@ccutrer I'm on vacation for a bit, but I'll take a look and reply thoughtfully next week.

**Comment by flavorjones** [comment]
This is on my to-do list! Apologies for the delay in responding.

**Comment by flavorjones** [comment]
Just an update: I'm going to spend time on this before cutting v1.19 which will probably stop exporting symbols (see https://github.com/sparklemotion/nokogiri/discussions/2746).

**Comment by ccutrer** [comment]
> Just an update: I'm going to spend time on this before cutting v1.19 which will probably stop exporting symbols (see [#2746](https://github.com/sparklemotion/nokogiri/discussions/2746)).

See also #3547, which is my current WIP. It looks like I have a minor conflict in ci.yml which I can resolve, but I need #3533 merged (and images built) before CI can pass anyway. I haven't had much time to work on this for a few weeks, but can probably pick it up quickly if you're wanting it done before 1.19.

**Comment by flavorjones** [comment]
@ccutrer Thank you for your patience with me! I just rebased #3533 and if it goes green it will get merged.

Right now I'm thinking hard about how to de-risk a change like this. I'm a little concerned about how/whether we can make the precompiled gem work with the variety of Ruby+OpenSSL installations.

I'm wondering if we should introduce "experimental support" for xmlsec in Nokogiri v1.19:

- ship a v1.19
  - introduce build arguments `--enable-xmlsec` and `--disable-xmlsec`
  - have it default to disabled, and do not ship it in the precompiled gem
  - get feedback from users who install it by compiling from source with the option enabled
- ALSO ship a v1.20 BETA at the same time
  - default it to enabled a nd ship it in the precompiled gem
  - get feedback from users

An alternative might be to have xmlsec as a separate gem somehow ... I need to re-familiarize myself with the technical issues there.

What do you think?

**Comment by flavorjones** [comment]
Also:

> I'm worried that [packaging OpenSSL into the gem] might cause weird conflicts with having two versions of it loaded into the same process.

It won't have any effect if we move forward with making symbols private (other than occupying some process memory -- but it will be shared memory across production server processes, and I think the linker does tree-shaking so it should only be the bits of OpenSSL that xmlsec uses).

**Comment by ccutrer** [comment]
I like the v1.19 xmlsec optional + v1.20.beta xmlsec default-enabled plan. That seems like a good de-risking strategy. I doubt participation would be very high. Personally I'd start using v1.20.beta immediately in order to use pre-compiled gems. But I worry that very few people would opt-in to enabling xmlsec on v1.19 otherwise. What if the pre-compiled v.1.19 has xmlsec disabled, but we still default-on for anybody that is not using pre-compiled? Someone compiling their own can more easily disable it if they run into issues. Maybe that's just an additional stepping stone in between opt-in-only and having xmlsec enabled in the pre-compiled gems?

As for separate gems, I attempted to modernize the build system of nokogiri-xmlsec-instructure modeling it after nokogiri proper, and it was a bit of a nightmare even before I could attempt it on macOS with the symbols issue. I could spend more time on it if we run into more issues or negative feedback about xmlsec being part of nokogiri, but for the sake of simplicity (and my sanity!) I would much prefer to just have it merged into nokogiri proper.
